#!/bin/bash

#HotSpot Tools
#20200425 KM4ACK
#side note: written during covid-19 outbreak of 2020


export MYPATH=$HOME/hotspot-tools2/
LOGO=$MYPATH/logo.png
VERSION=$(cat $MYPATH/changelog | grep version | head -1 | sed 's/version=//')

source $MYPATH/functions

yad --form --width=420 --text-align=center --center --title="Hot Spot Tools" --text-align=center \
--image $LOGO --window-icon=$LOGO --image-on-top --separator="|" --item-separator="|" \
--text="<b>Hot Spot Tools</b> by KM4ACK\rv$VERSION" \
--field="STATUS":RO "$HS" \
--field="STATE":RO "$HSS" \
--field="SSID":RO "$CURRENTNAME" \
--field="PASSWORD":RO "$CURRENTPASS" \
--field="IP ADDR":RO "$HSIP" \
--field="FORCE MODE":RO "$FORCE" \
--field="Change Name/Password":fbtn 'bash -c "kill -USR1 $YAD_PID; source $MYPATH/functions; namepwd"' \
--field="Run Hotspot Check":fbtn 'bash -c "kill -USR1 $YAD_PID; source $MYPATH/functions; hotspot"' \
--field="Force Hotspot":fbtn 'bash -c "kill -USR1 $YAD_PID; source $MYPATH/functions; FORCE"' \
--field="Undo Force Hotspot":fbtn 'bash -c "kill -USR1 $YAD_PID; source $MYPATH/functions; RESTORE"' \
--field="Disable Hotspot":fbtn "bash -c 'source $MYPATH/functions; disable'" \
--field="Enable Hotspot":fbtn "bash -c 'source $MYPATH/functions; enable'" \
--field="Manage SSIDs":fbtn 'bash -c "kill -USR1 $YAD_PID; source $MYPATH/functions; MANAGESSID"' \
--field="DHCP List":fbtn 'bash -c "kill -USR1 $YAD_PID; source $MYPATH/functions; DHCPLIST"' \
--field="Auto Hotspot Check <b>$AUTORUN</b>":fbtn 'bash -c "kill -USR1 $YAD_PID; source $MYPATH/functions; AUTOCHECK"' \
--button="QUIT":1

